channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python==3.9
  - pytorch==1.9.0
  - torchvision==0.10.0
  - torchaudio==0.9.0
  - numpy==1.20.3
  - matplotlib==3.4.3
  - tqdm==4.62.3
  - pillow==8.3.1